name: CI

on: [push, pull_request]

env:
  MAVEN_ARGS: -V -B --no-transfer-progress -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  test_jdk:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 13, 16]
    name: 'Linux JDK ${{ matrix.java }}'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: 'Test'
        run: ./mvnw ${MAVEN_ARGS} verify
  windows:
    name: 'Windows'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: 'Test'
        run: ./mvnw ${MAVEN_ARGS} verify
  mac:
    name: 'Mac OS'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: 'Test'
        run: ./mvnw ${MAVEN_ARGS} verify
